---
# tasks file for ansible_create_user
- name: create user {{ username110 }} and password {{ password110 }}
  user:
    name: "{{ username110 }}"
    shell: /bin/bash
    password: "{{ password110 | password_hash('sha512') }}"
    state: present
  register: user_added

- name: grant all privileges to user {{ username110 }} on sudoers
  copy:
    dest: /etc/sudoers.d/00_technical_user
    content: "{{ username110 }} ALL=(ALL)   NOPASSWD: ALL"

- name: "{{ username110 }} must change password on next login"
  shell: chage -d 0 "{{ username110 }}"
  when: user_added.changed
