---
# tasks file for ansible_create_user
- name: create user {{ newuser_username }} and password {{ newuser_password }}
  user:
    name: "{{ newuser_username }}"
    shell: /bin/bash
    password: "{{ newuser_password | password_hash('sha512') }}"
    state: present
  register: user_added

- name: grant all privileges to user {{ newuser_username }} on sudoers
  copy:
    dest: /etc/sudoers.d/00_technical_user
    content: "{{ newuser_username }} ALL=(ALL)   NOPASSWD: ALL"

- name: "{{ newuser_username }} must change password on next login"
  shell: chage -d 0 "{{ newuser_username }}"
  when: user_added.changed
